// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-2d6KbTjC6ZzwBsqLP2eFm2BT277PIVU',
    appId: '1:43234131637:web:6205a0eeb4b7ed26a0c8fc',
    messagingSenderId: '43234131637',
    projectId: 'bacakomik-reza',
    authDomain: 'bacakomik-reza.firebaseapp.com',
    storageBucket: 'bacakomik-reza.appspot.com',
    measurementId: 'G-L9MRFJNFRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAICwDwO5nPe8zuHBeaEbZjQZLb9HwEtVw',
    appId: '1:43234131637:android:d70193c5b964b3fba0c8fc',
    messagingSenderId: '43234131637',
    projectId: 'bacakomik-reza',
    storageBucket: 'bacakomik-reza.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB54Rh4zxWz9ULIIP3zp9c-U4yXhTFCz3U',
    appId: '1:43234131637:ios:862abcfdf0553ca0a0c8fc',
    messagingSenderId: '43234131637',
    projectId: 'bacakomik-reza',
    storageBucket: 'bacakomik-reza.appspot.com',
    iosClientId:
        '43234131637-dan55gcokab8tdj2c0112q1am5q547a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bacacomic',
  );
}
